# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: "ubuntu-18.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.14'
    
  - script: npm -v
    displayName: "Npm version"

  - script: yarn
    displayName: "Install dependencies"
  
  - script: yarn --production
    displayName: Prune dev dependencies

  - script: rm -rf coverage reports .vs .vscode docs src/__tests__
    displayName: Remove unnecessary folders

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
